baseURL: 'https://doug.gemignani.org/'
languageCode: en-us
title: Doug Blog
theme: even
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 2
params:
  rss: true
  headTitle: Douglas Lima
  colortheme: dark
  mainSections:
    - posts
  showAllPostsOnHomePage: true
  # showProjectsList:  true
  # projectsUrl:  "https://github.com/monkeyWzr"  
  mainSection: posts
  description: >-
    Hugo is a general-purpose website framework. Technically speaking, Hugo is a
    static site generator. Unlike systems that dynamically build a page with
    each visitor request, Hugo builds pages when you create or update your
    content. Since websites are viewed far more often than they are edited, Hugo
    is designed to provide an optimal viewing experience for your website’s end
    users and an ideal writing experience for website authors.
  socials:
    - name: Linkedin
      link: 'https://www.linkedin.com/in/douglas-lima-8a820a24/'
    - name: Github
      link: 'https://github.com/gemignani'
